# Generated by Django 5.1.7 on 2025-03-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankLoan',
            fields=[
                ('cus_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cus_name', models.CharField(max_length=100)),
                ('bankloan_no', models.IntegerField()),
                ('bankloan_amt', models.IntegerField()),
                ('dateofissue', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
